Default: &defaults
  database: nonoprint.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: nonoprint_test.sqlite3
  <<: *defaults

Staging:
  database: nonoprint_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: nonoprint_production.sqlite3
  poolsize: 100
  <<: *defaults
